[BBPBGLIB-1153] Allow disabling reports from SONATA config
BlueBrain/neurodamus pull request #156
Opened 2024-04-19 10:24 UTC by kbvw

## Context
This PR solves
https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-1153

According to the SONATA specification, reports can be disabled with an optional `enabled` parameter in the config file. This option was already parsed, but not used to disable the reports.

## Scope
A small change to the `enable_reports` method of the `Node` class, filtering the reports based on the `enabled` flag.

## Testing
An integration test in `tests/integration-e2e/test_reports.py`, reusing part of the existing fixture there and reading the flag from a SONATA config file.

## Review
* [ ] PR description is complete
* [ ] Coding style (imports, function length, New functions, classes or files) are good
* [ ] Unit/Scientific test added
* [ ] Updated Readme, in-code, developer documentation

2024-04-19 10:26 UTC, kbvw commented
The test is admittedly not completely end-to-end, but given the other tests there this seemed to me the most logical place to include it. Let me know if I should move it somewhere else.

2024-04-19 11:06 UTC, jorblancoa commented on tests/integration-e2e/test_reports.py
> +def sonata_config_synapse_report(sonata_config):
maybe better to call it sonata_config_new_report

2024-04-19 11:07 UTC, jorblancoa commented on tests/integration-e2e/test_reports.py
>          "synapse_report": {
Same here! new_report makes more sense
```
"new_report": {
```

2024-04-19 11:08 UTC, jorblancoa requested changes
Thanks for the contribution! I like the solution, just a couple of nitpicks! :)

2024-04-19 13:26 UTC, jorblancoa approved these changes

2024-04-22 08:44 UTC, WeinaJi approved these changes
LGTM. Thanks!

2024-04-22 08:58 UTC, WeinaJi commented
@kbvw , this PR can not trigger our GitLab CI tests because it is requested from the forked repo not the repo branch.
Have you been added to the BBP GH group ? If yes, can you open a PR from a neurodamus branch with the same commit? Sorry about that.

2024-04-22 09:20 UTC, kbvw commented
No worries, that's my bad. I just now got added: will open a new one.

2024-04-22 09:45 UTC, closed without merging

2024-04-22 09:46 UTC, kbvw commented
Closing in favour of #159.